Router.configure({
	layoutTemplate:'mainNav'
});
Router.route('/',function(){
	this.render('mainPage');
	this.layout('mainNav');
});
Router.route('/first',function () {
	this.render('firstPage');
	this.layout('mainNav');
	//this.layout('mainPage');
});
Router.route('/about_us',function(){
	this.render('about_us');
	this.layout('mainNav');
	//this.layout('mainSide');
});
Router.route('/clientPage',function(){
	this.render('clientPage');
	this.layout('mainNav');
	//this.layout('mainPage');
});
Router.route('/careerPage',function(){
	this.render('careerPage');
	this.layout('mainNav');
	//this.layout('mainSide');
	//this.layout('mainPage');
});
Router.route('/second',function(){
	this.render('secondPage');
	this.layout('mainSide');
	//this.layout('mainSide');
});
Router.route('/contact',function(){
	this.render('contact_us_page');
	this.layout('mainNav');
	//this.layout('mainSide');
	//this.layout('mainPage');
});